- name: python install and configure
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yml
- name: python app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml
- name: install python dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
- name: systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml

