- name: mysql repo copy
  ansible.builtin.template:
   src: roles/common/templates/mysql.repo
   dest: /etc/yum.repos.d/{{component}}.repo
- name: mysql server installation
  ansible.builtin.package:
    name:  "mysql-server"
    state: present
- name: mysql system service enable and start
  ansible.builtin.service:   
    name: mysqld
    enabled: yes
    state: restarted
- name: mysql set password
  ansible.builtin.shell:  mysql_secure_installation --set-root-pass "{{mysql_password}}"
- name: mysql connect
  ansible.builtin.shell:  mysql -uroot -p{{mysql_password}}