  - name: mysql repo copy
    ansible.inbuilt.copy:
      src: roles/common/templates/{{component}}.repo
      dest: /etc/yum.repos.d/{{component}}.repo
  - name: mysql repo copy
    ansible.inbuilt.package:
      name:  mysql-community-server
      state: present
  - name: mysql system service enable and start
    ansible.inbuilt.service:   
      name: mysqld
      enabled: yes
      state: restarted
  - name: mysql set password
    ansible.inbuilt.shell:  mysql_secure_installation --set-root-pass {{mysql_password}}
  - name: mysql connect
    ansible.inbuilt.shell:  mysql_secure_installation --set-root-pass {{mysql_password}}