- name: created local account
  ansible.builtin.shell:  useradd roboshop
- name: Create a directory  /app if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory
- name: Download {{component}}.zip
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp/{{component}}.zip
- name: Extract /tmp/{{component}}.zip into /app
  ansible.builtin.unarchive:
    src:   /tmp/{{component}}.zip
    dest:  /app
    remote_src: yes
- name: Install packages based on package.json
  npm:
    path: /app
- name: "copy {{component}} service content in /etc/systemd/system/{{component}}.service"
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service
