- name: stop the service {{component}}
  ansible.builtin.systemd_service:
    name: "{{component}}"
    state: stopped
  tags: deployment

- name: remove /app data
  ansible.builtin.file:
    path: /app
    state: absent
  tags: deployment



