- name: mongo copy repo
  ansible.builtin.copy:
    src: roles/common/files/mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: mongo client install
  ansible.builtin.shell: dnf install mongodb-org-shell -y
    
