- name: nginx installation
  ansible.builtin.package:
    name: nginx
    state: present
- name: deamon reloaded
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    daemon_reload: true
    enabled: true
- name: remove content from html
  ansible.builtin.file:
     path: /usr/share/nginx/html/*
     state: absent

