- name: nginx installation
  ansible.builtin.package:
    name: nginx
    state: present
- name: nginx service enable and start
  ansible.builtin.service:
     name: nginx
     enabled: yes
     state: started
- name: remove content from html
  ansible.builtin.file:
     path: /usr/share/nginx/html/*
     state: absent

